### ISSUE TITLE
TypeError: Bad argument for coloring SVG files in Windows 7

### ISSUE THREAD

**Issue by Kolombiken** [filamentgroup/grunticon#261]
When running Grunticon on Windows 7. I get the following error: 

```
Coloring SVG files                                                                                                                                              
TypeError: Bad argument                                                                                                                                         
    at TypeError (native)                                                                                                                                       
    at ChildProcess.spawn (child_process.js:1129:26)                                                                                                            
    at exports.spawn (child_process.js:988:9)                                                                                                                   
    at exports.execFile (child_process.js:682:15)                                                                                                               
    at c:\Project\node_modules\grunt-grunticon\node_modules\directory-colorfy\lib\colorfy.js:102:4         
    at $$$internal$$initializePromise (c:\Project\node_modules\grunt-grunticon\node_modules\directory-color
fy\node_modules\rsvp\dist\rsvp.js:538:9)                                                                                                                        
    at new $$rsvp$promise$$Promise (c:\Project\node_modules\grunt-grunticon\node_modules\directory-colorfy\
node_modules\rsvp\dist\rsvp.js:747:9)                                                                                                                           
    at Colorfy._getNewFileContents (c:\Project\node_modules\grunt-grunticon\node_modules\directory-colorfy\
lib\colorfy.js:100:10)                                                                                                                                          
    at c:\Project\node_modules\grunt-grunticon\node_modules\directory-colorfy\lib\colorfy.js:81:25         
    at $$$internal$$initializePromise (c:\Project\node_modules\grunt-grunticon\node_modules\directory-color
fy\node_modules\rsvp\dist\rsvp.js:538:9)                                                                                                                        
```

I have a simple file which uses colors and it looks like this `foo.colors-white.svg`

Tried using both Grunticon 2.1.6 and 2.1.3. Same result. Works well on OSX though.

**Comment by jefflembeck** [comment]
@Kolombiken any chance you can upload the file for me to try?

Also, which Node version?

**Comment by Kolombiken** [comment]
@jefflembeck 

Thank you for the quick reply!

Here's the file http://cl.ly/3417153r3l3r

I've tried on different Windows-machines with different versions of nNode. Both 0.10.32, 0.10.38 and 0.12.1. They are all getting the same error.

**Comment by CrispyBacon12** [comment]
Just experienced the same issue, immediately following an npm install. The PhantomJS installed for directory-colorfy had failed to create a location.js, there had been several other errors during the install. Clearing npm cache and reinstalling fixed it all for me.

```
sudo npm cache clean
npm install
```
