### ISSUE TITLE
npm ERR! 404 'filamentgroup' is not in the npm registry.

### ISSUE THREAD

**Issue by bramwillemse** [filamentgroup/grunticon#269]
Hi there,

I'm trying to install grunt-grunticon on a Windows 7 machine and I'm running into the error below. N00b as I am I'm stuck already. I googled these errors but I'm not sure where to look next.

```
npm WARN optional dep failed, continuing imagemin-jpegtran@4.2.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm WARN optional dep failed, continuing imagemin-pngquant@4.1.0
npm ERR! 404 404 Not Found: filamentgroup
npm ERR! 404
npm ERR! 404 'filamentgroup' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'directory-colorfy'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-grunticon"
npm ERR! cwd C:\KvK\workspace\KVK2014
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```

**Comment by jefflembeck** [comment]
@bramwillemse can you run `npm install -g npm@latest` from your command line and let me know if that fixes your issue?

**Comment by bramwillemse** [comment]
@jefflembeck thanks for the quick response. I did and got the same error, but with some more before it: 

```
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
> pngquant-bin@3.0.0 postinstall C:\<WORKINGDIR>\node_modules\grunt-gru
nticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\imagemin\
node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node lib/install.js

 ‼ Request to https://raw.github.com/imagemin/pngquant-bin/v3.0.0/vendor/win/pn
gquant.exe failed
 ‼ pngquant pre-build test failed
 i compiling from source
 × GotError: pngquant failed to build, make sure that libpng-dev is installed
   at ClientRequest.<anonymous> (C:\<WORKINGDIR>\node_modules\grunt-gr
unticon\node_modules\grunticon-lib\node_modules\svg-to-png\node_modules\imagemin
\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-build
\node_modules\download\node_modules\got\index.js:177:7)
   at ClientRequest.g (events.js:180:16)
   at ClientRequest.emit (events.js:95:17)
   at CleartextStream.socketErrorListener (http.js:1551:9)
   at CleartextStream.emit (events.js:95:17)
   at SecurePair.<anonymous> (tls.js:1397:15)
   at SecurePair.emit (events.js:95:17)
   at SecurePair.error (tls.js:1017:27)
   at EncryptedStream.CryptoStream._done (tls.js:702:22)
   at CleartextStream.read [as _read] (tls.js:498:24)
Caused By: Error: socket hang up
   at SecurePair.error (tls.js:1010:23)
   at EncryptedStream.CryptoStream._done (tls.js:702:22)
   at CleartextStream.read [as _read] (tls.js:498:24)
   at CleartextStream.Readable.read (_stream_readable.js:340:10)
   at EncryptedStream.onCryptoStreamFinish (tls.js:303:47)
   at EncryptedStream.g (events.js:180:16)
   at EncryptedStream.emit (events.js:117:20)
   at finishMaybe (_stream_writable.js:359:12)
   at endWritable (_stream_writable.js:366:3)
   at EncryptedStream.Writable.end (_stream_writable.js:344:5)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.2.0
npm ERR! 404 404 Not Found: filamentgroup
npm ERR! 404
npm ERR! 404 'filamentgroup' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'directory-colorfy'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-grunticon"
npm ERR! cwd C:\<WORKINGDIR>
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
```

**Comment by jefflembeck** [comment]
@bramwillemse - so, i'm seeing

```
‼ Request to https://raw.github.com/imagemin/pngquant-bin/v3.0.0/vendor/win/pn
gquant.exe failed
```

Are you behind a firewall at all or on a shaky connection?

**Comment by bramwillemse** [comment]
Good connection, but we're working behind a proxy here. Proxy (http / https) is set correctly though (or npm installs wouldn't work at all)

**Comment by jefflembeck** [comment]
@bramwillemse can you try that above url? (https://raw.github.com/imagemin/pngquant-bin/v3.0.0/vendor/win/pngquant.exe)

**Comment by bramwillemse** [comment]
@jefflembeck Yes, I'm able to download it in my browser.

**Comment by jefflembeck** [comment]
@bramwillemse can you also try `npm --version` for me?

**Comment by jefflembeck** [comment]
I ask because scoped modules are only available in newer versions of npm and I saw that, despite you running `npm install -g npm@latest`, that the error is saying you're on version 1.4

**Comment by bramwillemse** [comment]
@jefflembeck you're right. Still on 1.4: 1.4.28

**Comment by jefflembeck** [comment]
bizarre. what does it say when you run that command?

**Comment by bramwillemse** [comment]
only this: 

```
C:\Users\username\AppData\Roaming\npm\npm -> C:\Users\username\AppData\Roaming\npm\n
ode_modules\npm\bin\npm-cli.js
npm@2.11.2 C:\Users\dbxbwi\AppData\Roaming\npm\node_modules\npm
```

**Comment by bramwillemse** [comment]
I'm trying to install the latest nodejs.exe right now. Maybe that helps..

**Comment by bramwillemse** [comment]
It worked :) As simple as an update. But so weird they don't give an error message when you try to update.. I'll be happy when I'm back on my mac after this project. 

Thanks for the super quick help, @jefflembeck!

**Comment by jefflembeck** [comment]
@bramwillemse Woo hoo! Glad I could be of service.
